apiVersion: v1
kind: Pod
metadata:
  name: adm100
  labels:
    dt: hdp
spec:
  hostname: adm100
  subdomain: hdp 
  containers:
  - name: adm100
    image: dt210.img
    ports:
    - containerPort: 22
      hostPort: 22100
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "3072Mi"
    stdin: true
    tty: true
    volumeMounts:
    - name: opt
      mountPath: /home/bigred/
      subPath: adm100
    - name: opt
      mountPath: /opt/dataset
      subPath: dataset
    - name: dtbin
      mountPath: /opt/bin
    - name: dtconf
      mountPath: /opt/hadoop-2.10.1/etc/hadoop/
      subPath: hdp210
    - name: dtconf
      mountPath: /opt/hbase-1.4.13/conf/
      subPath: hbconf
    - name: dtconf
      mountPath: /opt/apache-zookeeper-3.6.2-bin/conf/
      subPath: zkconf
    - name: dtconf
      mountPath: /opt/spark-3.0.1-bin-hadoop2.7/conf
      subPath: spkconf
    command:
    - "/bin/bash"
    - "-c"
    - |
      cp -r /etc/skel/. /home/bigred;
      /bin/bash
  volumes:
   - name: dtconf
     hostPath:
       path: /home/bigred/dt/conf
   - name: dtbin
     hostPath:
       path: /home/bigred/dt/bin
   - name: opt
     hostPath:
       path: /opt
  dnsConfig:
    searches:
    - hdp.hdp.svc.sre
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-84-k3m84
  restartPolicy: Never
