apiVersion: v1 
kind: Pod 
metadata: 
 name: sqldb 
 labels: 
  app: mariadb 
spec: 
  containers:
    - name: sqldbc 
      image: quay.io/cloudwalker/mariadb 
      imagePullPolicy: IfNotPresent 
      env:
        - name: MYSQL_DATABASE 
          value: datatest
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports: 
        - containerPort: 3306 
          hostPort: 3306
      volumeMounts:
        - name: mariadb-dir 
          mountPath: /var/lib/mysql
  volumes: 
   - name: mariadb-dir 
     hostPath: 
       path: /opt/pv/mariadb
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-94-k3w94
---
apiVersion: v1
kind: Service
metadata:
  name: sqldb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
